### ISSUE TITLE
get data from excel file and than will be a practical software

### ISSUE THREAD

**Issue by qaisbayabani** [XCharts-Team/XCharts#327]
where have to put the logic from which the chart has been taking the data and why dont you convert it to take data from access database or excel csv

**Comment by monitor1394** [comment]
Yes, that's a great suggestion.

At the current stage, XCharts is positioned as a plugin rather than an application. Our aim with XCharts is to ensure that it remains lightweight while still being capable of correctly rendering charts across various versions and platforms.

Data sources can be diverse, including files, databases, servers, and more. To support such a wide range of sources, we would inevitably need to introduce more code, which could lead to increased compatibility issues. Not every user might require these additional functionalities.

For now, our focus is on optimizing and implementing the charting features. It's possible that in future versions, we might introduce data reading support through extension features, but it may not be directly integrated into the core library of XCharts.

We appreciate your feedback and will keep it in mind as we continue to develop and enhance XCharts.

Thank you for your understanding and for contributing to the project.
